# Generated by Django 3.0.7 on 2020-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildlogentry',
            name='slug',
            field=models.SlugField(default='new_post', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='buildlogentry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
