# Generated by Django 3.0.7 on 2020-07-14 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BuildLog', '0002_auto_20200714_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildlogentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildlog_buildlogentry_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
